backend:
  commands:
    - mkdir backend
    - cd backend
    - npm init -y
    - npm install express mongoose nodemon
  files:
    ./.gitgnore: |
      node_modules
    ./index.js: |
      console.log("MERN Config")
frontend:
  commands:
    - npx create-vite frontend --template react
    - cd frontend
    - npm install
    - npm install tailwindcss postcss autoprefixer
    - npx tailwindcss init -y
  files:
    ./.gitignore: |
      node_modules
      dist
      dist-ssr
      *.local
    ./package.json: |
      {
        ...,
        "scripts": {
          "dev": "npx vite",
          "build": "npx vite build",
          "lint": "eslint . --ext js,jsx --report-unused-disable-directives --max-warnings 0",
          "preview": "npx vite preview"
        },
        ...
      }
    ./postcss.config.js: |
      export default {
        plugins: {
          tailwindcss: {},
          autoprefixer: {},
        },
      };
    ./tailwind.config.js: |
      /** @type {import('tailwindcss').Config} */
      export default {
        content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
        theme: {
          extend: {},
        },
        plugins: [],
      };
    ./index.html: |
      <!DOCTYPE html>
      <html lang="en">
        <head>
          <meta charset="UTF-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <title>MERN Config</title>
        </head>
        <body>
          <div id="root"></div>
          <script type="module" src="/src/main.jsx"></script>
        </body>
      </html>
    src/index.css: |
      @tailwind base;
      @tailwind components;
      @tailwind utilities;

      :root {
        font-family: Inter, system-ui, Avenir, Helvetica, Arial, sans-serif;
        line-height: 1.5;
        font-weight: 400;

        color-scheme: light dark;
        color: rgba(255, 255, 255, 0.87);
        background-color: #242424;

        font-synthesis: none;
        text-rendering: optimizeLegibility;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
      }
    src/App.jsx: |
      function App() {
        return <></>;
      }

      export default App;

  delete:
    - ./App.css
    - public/
    - src/assets/
